spring:
  application:
    name: cloud-storage-in-action
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

gcp:
  project-id: ###
  credentials-location: ###
  bucket-id: ####
