spring:
  application:
    name: cloud-storage-in-action
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

gcp:
  project-id: zaki-01-486806
  credentials-location: /zaki-01-486806-762ec8b740ec.json
  bucket-id:  image-db-2003